### ISSUE TITLE
Install issue on CentOS7/

### ISSUE THREAD

**Issue by davidjp90** [jakeogh/dnsgate#4]
Hi jakeogh

After installing kcl from your github i get the following error when generating the configuration:

dnsgate --verbose generate
Traceback (most recent call last):
  File "/usr/bin/dnsgate", line 9, in <module>
    load_entry_point('dnsgate==0.0.1', 'console_scripts', 'dnsgate')()
  File "/usr/lib/python3.4/dist-packages/click-6.7-py3.4.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/dist-packages/click-6.7-py3.4.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/dist-packages/click-6.7-py3.4.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/dist-packages/click-6.7-py3.4.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/dist-packages/click-6.7-py3.4.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/dist-packages/click-6.7-py3.4.egg/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/lib/python3.4/dist-packages/dnsgate-0.0.1-py3.4.egg/dnsgate/dnsgate.py", line 332, in generate
    eprint('Using output file: %s', config.output, level=LOG['INFO'])
  File "/usr/lib/python3.4/dist-packages/kcl-0.1-py3.4.egg/kcl/printops.py", line 23, in eprint
    print(*args, file=sys.stderr, **kwargs)
TypeError: 'level' is an invalid keyword argument for this function

Running Python3.4, installed setuptools, devel.
I'm using Centos7/Amazon AMI - both get to the same place and fail.

Let me know if you need any more info.

Thanks,
David

**Comment by jakeogh** [comment]
Thanks for the report! This should be fixed, please re-install kcl and dnsgate. kcl is still in flux, although I use it on most of my projects. I'll work on better testing next time I change it.

-Justin

**Comment by davidjp90** [comment]
Thanks for the response Justin. It now seems to be working.

Thanks,
David
